[[redirects]]
	from = "/en/*"
	to = "/en/404/"
	status = 404

[[redirects]]
	from = "/cs/*"
	to = "/cs/404/"
	status = 404

[[redirects]]
	from = "/*"
	to = "/en/404/"
	status = 404

[build]
publish = "frontend/public"
command = "cd frontend && hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.79.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
